<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [3]:
def basic_stats(numbers):
    np_numbers = np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

print(basic_stats((1,2,3,4,5)))

def greeting(name):
    return f"Hello {name}, nice to meet you"

print(greeting(input("What is your name")))

(1, 5, 3.0)
What is your nameLol
Hello Lol, nice to meet you


### 1.2 Named functions that don’t return

In [4]:
def hello_world(name):
    print("Hello "+name)

hello_world("yugan")

Hello yugan


### 1.3 Anonymous functions

In [5]:
funcf = lambda x: f"Hello {x}"
print(funcf("Yugan"))



'Hello Yugan'

In [10]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

print(sorted(numbers))                         # Sort by comparing the default key 
                                               # (i.e. the 1st element) 
    
x = sorted(numbers, key = lambda x: np.array(x).mean())
list(map(lambda x: sorted(x), x))

[[0, 9, 19], [1, 8, 18], [2, 7, 17], [3, 6, 16], [4, 5, 15], [5, 4, 14], [6, 3, 13], [7, 2, 12], [8, 1, 11], [9, 0, 10]]


[[0, 9, 10],
 [1, 8, 11],
 [2, 7, 12],
 [3, 6, 13],
 [4, 5, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [17]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

print('---'.join(greeting().split()))

Hello---no---one!


## 2 The importance of functions?

### 2.1 An argument for functions

In [19]:
#abstraction 


l = []
l.append(1)
l.append(2)
l.append(3)
l.append(4)
print(l)

def abstracted():
    l = []
    l.extend([1,2,3,4])
    return l

newl = abstracted()
print(newl)

[1, 2, 3, 4]
[1, 2, 3, 4]


### 2.2 A word of caution

In [24]:
def misuse(a, b, c, d, e, f):
    n = a+b+c+d+e+f
    return eval(n)

print(misuse("1", "+", "2", "3", "-", "5"))

def correct(lis):
    a,b,c,d,e,f = lis
    return eval(a+b+c+d+e+f)
print(correct(["1", "+", "2", "3", "-", "5"]))

19
19


## Exercise 1 :  Do you know why?

In [ ]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

Whenever a return statement is reached, the function is exited, so there will never be a case where both return statements are run at the same time

## Exercise 2 :  Calculator functions

In [15]:
def add(x,y):
    return x+y

def substract(x,y):
    return add(x,-y)

def multiply(x,y):
    return x*y

def divide(x,y):
    if y.any(0):
        return "You have inputted a 0" #superior to exit()/quit() as the code is saved and the function doesnt run
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
print(add(x,y))
print(substract(x,y))
print(multiply(x,y))
print(divide(x,y))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [18]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(n):
    return (np.max(n), np.argmax(n))
max_info(numbers)

(83, 2)