<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]

np_array = np.array(py_list)

x = np_array
x[-1]

x[5:2:-1] # output = array(['f6', 'e5', 'd4'], dtype='<U3') U is unicode, a superset of ascii

array(['f6', 'e5', 'd4'], dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [21]:
py_list = [i for i in range(1,10)]
np_array = np.array(py_list)
my_mask = np_array > 3

print(list(filter(lambda x: x>3, py_list)))
print(np_array[my_mask])
print(list(filter(lambda x: x>5, py_list)))
print(np_array[np_array>5])

print(np_array[~(np_array>5)]) #[1,2,3,4,5]
print(np_array[~(np_array>5) & (np_array>3)]) #[1,2,3,4,5] & [4,5,6,7,8,9,10]
print(np_array[~(np_array>4) | (np_array>5)]) #without 5

[4, 5, 6, 7, 8, 9]
[4 5 6 7 8 9]
[6, 7, 8, 9]
[6 7 8 9]
[1 2 3 4 5]
[4 5]
[1 2 3 4 6 7 8 9]


### 1.3 Indexing & Slicing 2D Lists

In [29]:
py = [[1, "A"], [2, "B"], [3, "C"], [4, "D"], [5, "E"], [6, "F"], [7, "G"], [8, "H"],[9, "I"], [10, "J"]]

print(py[:5:-1][1]) #[[10, 'J'], [9, 'I'], [8, 'H'], [7, 'G']][1] = [9, "I"]
print(py[2:4][0]) # [[3, "C"], [4,"D"]][0] = [3, "C"]

[9, 'I']
[[3, 'C'], [4, 'D']]


### 1.4 Indexing & Slicing 2D Arrays

In [48]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[0,0]
print(np_array_2d[:3,0])
print(np_array_2d[:,1])
print(list(map(list, zip(*py)))[1])

['1' '2' '3']
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']


### 1.5 Growing lists

In [50]:
x = [1]*10
x

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [62]:
x = [1,1]
x.extend([i for i in range(5)])
x.append(5)
print(x)

[1, 1, 0, 1, 2, 3, 4, 5]


## 2 Some loose ends

### 2.1 Tuples

In [68]:
a = (1,2,3)
a += (3,)
#a[0] -=1 Error

### 2.2 Be VERY careful when copying

In [75]:
x = [1,2,3, [2,3,4]]
y = x.copy()
print(y)
from copy import deepcopy
z = deepcopy(x) #to copy all elements including within list of lists
print(z)

[1, 2, 3, [2, 3, 4]]
[1, 2, 3, [2, 3, 4]]


## Exercise 1 :  Total recall?

Subsetting - to select an element or a set of elements from an array/list
Indexing - to select a single element from the list
Slicing	- to select a set of elements from an array/list
Masking - to select an element or a set of elements that satisfies a predicate function

## Exercise 2 :  Show me the ‘odd’ letters

In [101]:
n = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
#method 1
print(np.array(list(filter(lambda x: int(x[0])%2, n)))[:,1])

#method 2
a = n[:,0] # to get array(['1', '3', '2', ..., '10', '9'])
a = a.astype(int) #to convert to int
a = a%2 # output [1,1,0,0,1,1,0,0,0,1]
print(n[a==1][:,1]) #output mask [['1' 'A'], ['3' 'C'], ['5' 'E'], ['7' 'G'], ['9' 'I']] and takes the 1th element 


['A' 'C' 'E' 'G' 'I']
['A' 'C' 'E' 'G' 'I']


In [87]:
print(np.array(list(filter(lambda x: int(x[0])%2, n))))

[['1' 'A']
 ['3' 'C']
 ['5' 'E']
 ['7' 'G']
 ['9' 'I']]
