<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [21]:
import numpy as np

print(np.array([i for i in range(10)]))
print([i for i in range(10)])
print(dict([(i, str(i)+'  number') for i in range(5)]))

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info)

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
{0: '0  number', 1: '1  number', 2: '2  number', 3: '3  number', 4: '4  number'}
dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])


### 1.2 Accessing data from a list (or array)

In [23]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [36]:
print(py_super_names[0]) # to find the element in the list from its index
print(py_super_names.index("Black Widow")) # to find the index of the element from the element 

Black Widow
0


In [26]:
py_real_names[-2]

'Tony Stark'

### 1.3 Accessing data from a dictionary

In [27]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [39]:
print(superhero_info["Tony Stark"])     # to find the value of the key
for i in superhero_info:                # to find the key of the dictionary from its value
    if superhero_info[i] == "Iron Man":
        print(i)

Iron Man
Tony Stark


In [34]:
print(superhero_info.keys())
print(superhero_info.values())

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


### 1.4 Higher dimensional lists

In [43]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)
print(np_array_2d)
print(np_array_2d.flatten()) # to collapse the 2d array into a singular array

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]
['1' 'A' '2' 'B' '3' 'C' '4' 'D' '5' 'E' '6' 'F' '7' 'G' '8' 'H' '9' 'I'
 '10' 'J']


## 2 Lists vs. Arrays

### 2.1 Size

In [24]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

print(len(np_array_2d)==len(py_list_2d)==10)

print(np_array_2d.shape)

print(np_array_2d.reshape((2,10))) #reshapes the matrix to one with 2 rows and 10 columns
print(np_array_2d.reshape(-1)) # flattens the list
print(np_array_2d.transpose()) # transposes the matrix 

True
(10, 2)
[['1' 'A' '2' 'B' '3' 'C' '4' 'D' '5' 'E']
 ['6' 'F' '7' 'G' '8' 'H' '9' 'I' '10' 'J']]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']
 ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']]


### 2.2 Arrays are fussy about type

In [79]:
py_list = [(1,2),True, False, 5]
#print(np.array(py_list)) Error as different types were used and dtype wasnt' specified

py_list = [True, False, 5, '2']
print(np.array(py_list, dtype = 'int')) #converts every element to be an int
print(np.array(py_list, dtype = 'object')) #type of every element is an object (tuple, int, str)
print(np.array(py_list, dtype = 'bool')) # every type is a bool

[1 0 5 2]
[True False 5 '2']
[ True False  True  True]


### 2.3 Adding a number

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

print(np_array+10)
print(list(map(lambda x: x+ 10, py_list)))
#print(py_list + 10)  error as the types are different 


[11 12 13 14 15]
[11, 12, 13, 14, 15]


### 2.4 Adding another list

In [57]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2) 

print(py_list_1+ py_list_2)
print(np.concatenate((np_array_1, np_array_2)))
print(list(map(lambda x,y: x+y, py_list_1, py_list_2)))
print(np_array_2 + np_array_1)
print(py_list_1 + np_array_2)# converts py_list_1 to be an numpy.ndarray 

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[ 1  2  3  4  5 10 20 30 40 50]
[11, 22, 33, 44, 55]
[11 22 33 44 55]
[11 22 33 44 55]


### 2.5 Multiplying by a Number

In [74]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print(py_list*3)
print(list(map(lambda x: x*3, py_list)))
print(np_array*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[3, 6, 9, 12, 15]
[ 3  6  9 12 15]


### 2.6 Squaring

In [80]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print(list(map(lambda x: x**2, py_list)))
print(np_array**2)


[1, 4, 9, 16, 25]
[ 1  4  9 16 25]


### 2.7 Asking questions

In [82]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

False

In [83]:
np_array >3

array([False, False, False,  True,  True])

In [87]:
list(map(lambda x: x>3, py_list))

[False, False, False, True, True]

In [88]:
np.array_equal(py_list,np_array) # same as comparing 2 lists

True

### 2.8 Mathematics

In [98]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print(np_array.mean())
print(np_array.sum())

3.0
15


## Exercise 1 :  Total recall?

Purely from memory, jot down:

Two similarities between lists and arrays.
1. Lists and arrays are mutable, their individual elements can be changed
2. Lists and arrays hold a list of elements which can be indexed and sliced
Two differences between lists and arrays.
1. Lists can hold elements of various types (ints, other lists, strings), whereas arrays can only hold elements of a singular type(string, int, objects)
2. array manipulation(addition and multiplication) changes every element of the array whereas list manipulation(addition and multiplication) changes the list itself, either adding lists onto itself or repeating lists 

What is a dictionary?
dictionary is a data structure that has key-value pairs the keys must be of an immutable data type (int, str, tuples) whereas the values can be of any data type including other dictionaries

## Exercise 2 :  Index me

In [100]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [102]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

for i in superhero_info:
    superhero_info[i] = superhero_info[i].upper()

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [107]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]

print(numbers.count(1))
print(sum(np.array(numbers)==1))

9
9
